iname: Test AWS OIDC Access

on:
  push:
    branches: [ main ]

permissions:
  id-token: write     
  contents: read      

jobs:
  aws-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::702865854817:role/amrit-OIDC 
          aws-region: us-east-1

      - name: Show AWS identity
        run: aws sts get-caller-identity
 
      - name: List contents of S3 bucket
        run: aws s3 ls s3://amrit-lf
